### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by DennisZP** [gstf/libspatialite-ios#8] opened 2015-04-14 10:55 UTC
I also experienced the above problems,

configure: error: 'libxml2' is required but it doesn't seem to be installed on this system.
make[1]: *** [/Users/lz/OpenSource/libspatialite-ios/build/armv7/lib/libspatialite.a] Error 1
make: *** [build_arches] Error 2

run "brew install libxml2" after,How should I do,Could you give a detailed process!
Thanks so much!

**Comment by muellermartin** [comment] 2015-04-14 11:13
This is a duplicate of issue #7 – therefore closing this one.
See #7 for further discussion and please try to use helpful issue names ("HELP" is not a good title).
Thanks

**Closed by muellermartin** 2015-04-14 11:13 UTC
